#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Token<'a> {
    Number(f64),
    Plus,
    Minus,
    Star,
    Slash,
    DoubleSlash,
    Percent,
    EqualEqual,
    NotEqual,
    GreaterEqual,
    LessEqual,
    Greater,
    Less,
    Dice,
    DicePercent,
    Keep,
    Drop,
    Reroll,
    RerollOnce,
    RerollAdd,
    Explode,
    Min,
    Max,
    SelectorHigh,
    SelectorLow,
    LParen,
    RParen,
    SetStart,
    SetEnd,
    Comma,
    AnnotationStart,
    AnnotationText(&'a str),
    AnnotationEnd,
    Eof,
}
